#!/system/bin/sh


swapoff /dev/block/zram1;
swapoff /dev/block/zram2;
swapoff /dev/block/zram3;
swapoff /dev/block/zram0;

echo 1 > /sys/block/zram1/reset;
echo 536870912 > /sys/block/zram1/disksize;
mkswap /dev/block/zram1;

echo 1 > /sys/block/zram2/reset;
echo 536870912 > /sys/block/zram2/disksize;
mkswap /dev/block/zram2;

echo 1 > /sys/block/zram3/reset;
echo 536870912 > /sys/block/zram3/disksize;
mkswap /dev/block/zram3;

echo 1 > /sys/block/zram0/reset;
echo 536870912 > /sys/block/zram0/disksize;
mkswap /dev/block/zram0;

/system/xbin/busybox swapon -p 2 /dev/block/zram0;
/system/xbin/busybox swapon -p 2 /dev/block/zram3;
/system/xbin/busybox swapon -p 2 /dev/block/zram2;
/system/xbin/busybox swapon -p 2 /dev/block/zram1;

echo 100 > /proc/sys/vm/swappiness;
exit
