#!/system/bin/sh
 
echo 1 > /sys/block/zram1/reset;
echo 104857600 > /sys/block/zram1/disksize;

echo 1 > /sys/block/zram2/reset;
echo 104857600 > /sys/block/zram2/disksize;

echo 1 > /sys/block/zram3/reset;
echo 104857600 > /sys/block/zram3/disksize;

echo 1 > /sys/block/zram0/reset;
echo 104857600 > /sys/block/zram0/disksize;
 
echo 100 > /proc/sys/vm/swappiness;
 
exit
